"""Fine-tune the vocoder (Vocos or BigVGAN-v2) on mels generated by the trained TTS model ("GTA" fine-tuning).

The frozen TTS model produces mels for training utterances under the *ground-truth* alignment
(teacher-forced durations), so every generated frame lines up with the recorded waveform. The
vocoder is then trained to turn the model's (smoother) mels into the real audio with its original
GAN objective:

- ``vocos``: fresh multi-period and multi-resolution discriminators (none were released), hinge
  loss, feature matching and an L1 log-mel loss, after a discriminator warm-up. A Vocos vocoder can also be
  trained on BigVGAN mels (``vocoder.arch: vocos`` with a BigVGAN-mel TTS model): its ISTFT head then uses
  ``same`` padding, which centres frame ``i`` on sample ``i * hop + hop / 2`` as BigVGAN's uncentred STFT does.
- ``bigvgan``: resumes NVIDIA's released generator *and* discriminators (MPD + multi-scale sub-band
  CQT) with their AdamW states, as the official recipe does; LSGAN, feature matching and the
  multi-scale mel L1 (x15), at the learning rate where the released schedule ended.

``vocoder.objective: drift`` trains either architecture without a GAN (:class:`DriftVocoder`, ``drift_vocoder.py``).
"""

from __future__ import annotations

import argparse
import itertools
import time
from contextlib import nullcontext
from pathlib import Path

import torch
from torch.utils.data import DataLoader

from .alignment import sequence_mask
from .audio import HOP_LENGTH, SAMPLE_RATE
from .config import load_config, save_config
from .data import BucketBatchSampler, MelDataset, collate
from .models import bigvgan_disc as bd
from .models.text_encoder import align, token_pitch
from .utils import count_params, infinite, save_checkpoint, seed_everything
from .vocoder import BIGVGAN_REPO, build_bigvgan, build_vocos

OBJECTIVES = ("gan", "drift")


def add_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--config", default="configs/vocoder.yaml")
    p.add_argument("--workdir", default="runs/vocoder")
    p.add_argument("overrides", nargs="*", help="config overrides, e.g. train.steps=1000")


@torch.no_grad()
def gta_mels(tts, batch: dict, temperature: float, device, cfg_scale: float = 1.0, steps: int | None = None,
             generator: torch.Generator | None = None) -> torch.Tensor:
    """Teacher-forced (ground-truth alignment) generated mels ``[B, n_mels, T]`` (normalised).

    Pitch-conditioned models use the ground-truth pitch from ``batch["f0"]``, or the predicted pitch without it."""
    text, text_len = batch["text"].to(device), batch["text_len"].to(device)
    y, y_len, spk = batch["mel"].to(device), batch["mel_len"].to(device), batch["spk"].to(device)
    y_mask = sequence_mask(y_len, y.shape[-1])
    h, mu, _, x_mask = tts.encoder(text, text_len, spk)
    attn, _ = align(mu, x_mask, y, y_mask[:, None].float())
    if tts.pitch_enabled:
        lf0_mean, lf0_std = tts.lf0_stats.tolist()
        pitch = token_pitch(batch["f0"].to(device), attn, lf0_mean, lf0_std) if "f0" in batch else None
        h, _ = tts.pitch_condition(h, x_mask, spk, pitch)
    cond = tts.frame_condition(h, mu, attn)
    z = torch.randn(y.shape[0], y.shape[1], y.shape[-1], device=device, generator=generator) * temperature
    alpha = torch.full((y.shape[0],), float(cfg_scale), device=device)
    steps = tts.generator.num_steps if steps is None else steps
    return tts.rollout(z, cond, spk, alpha, steps, generator=generator, mask=y_mask) * y_mask[:, None]


def segment_samples(frames: int, backend: str = "vocos") -> int:
    """Waveform samples produced from ``frames`` mel frames. Vocos (centred STFT, ISTFT head): frame ``i`` is centred
    on sample ``i * hop``, so ``F`` frames <-> ``(F - 1) * hop`` samples. BigVGAN (reflect-padded uncentred STFT,
    256x upsampler): frame ``i`` is centred on ``i * hop + hop / 2``, so ``F`` frames <-> ``F * hop`` samples."""
    return (frames - 1) * HOP_LENGTH if backend == "vocos" else frames * HOP_LENGTH


def random_segments(mel: torch.Tensor, audio: torch.Tensor, mel_len: torch.Tensor, frames: int,
                    backend: str = "vocos"):
    """Aligned random windows: mel frames ``[s, s + frames)`` <-> samples ``[s * hop, s * hop + n)``."""
    B = mel.shape[0]
    starts = (torch.rand(B) * (mel_len.cpu() - frames + 1).clamp_min(1).float()).long()
    n = segment_samples(frames, backend)
    m = torch.stack([mel[i, :, s: s + frames] for i, s in enumerate(starts.tolist())])
    a = torch.stack([audio[i, s * HOP_LENGTH: s * HOP_LENGTH + n] for i, s in enumerate(starts.tolist())])
    return m, a


class VocosGAN:
    """Vocos generator + fresh MPD / MRD: hinge + feature matching + 45 x log-mel L1 (the Vocos recipe)."""

    backend, export_name = "vocos", "vocos_ft.pt"

    def __init__(self, cfg, device, mel: str = "vocos"):
        from vocos.discriminators import MultiPeriodDiscriminator, MultiResolutionDiscriminator
        from vocos.loss import DiscriminatorLoss, FeatureMatchingLoss, GeneratorLoss, MelSpecReconstructionLoss

        self.cfg, tc, self.mel = cfg, cfg.train, mel
        self.vocos = build_vocos(cfg.vocoder.init).to(device).train()
        if mel == "bigvgan":  # F frames <-> F * hop samples, frame i centred on i * hop + hop / 2
            self.vocos.head.istft.padding = "same"
        self.mpd, self.mrd = MultiPeriodDiscriminator().to(device), MultiResolutionDiscriminator().to(device)
        self.gen_params = list(self.vocos.backbone.parameters()) + list(self.vocos.head.parameters())
        self.opt_g = torch.optim.AdamW(self.gen_params, lr=tc.lr, betas=(0.8, 0.9))
        self.opt_d = torch.optim.AdamW(list(self.mpd.parameters()) + list(self.mrd.parameters()), lr=tc.lr,
                                       betas=(0.8, 0.9))
        self.disc_loss, self.gen_loss, self.fm_loss = DiscriminatorLoss(), GeneratorLoss(), FeatureMatchingLoss()
        self.mel_loss = MelSpecReconstructionLoss(sample_rate=SAMPLE_RATE).to(device)
        self.n_gen, self.n_disc = count_params(self.vocos), count_params(self.mpd) + count_params(self.mrd)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:  # Vocos.decode runs under inference_mode
        return self.vocos.head(self.vocos.backbone(mel))

    def step(self, mel: torch.Tensor, audio: torch.Tensor, step: int) -> dict:
        tc = self.cfg.train
        with torch.no_grad():
            audio_hat = self.generate(mel)
        r_mp, g_mp, _, _ = self.mpd(y=audio, y_hat=audio_hat)
        r_mr, g_mr, _, _ = self.mrd(y=audio, y_hat=audio_hat)
        l_mp, l_mp_r, _ = self.disc_loss(disc_real_outputs=r_mp, disc_generated_outputs=g_mp)
        l_mr, l_mr_r, _ = self.disc_loss(disc_real_outputs=r_mr, disc_generated_outputs=g_mr)
        l_d = l_mp / len(l_mp_r) + tc.mrd_loss_coeff * l_mr / len(l_mr_r)
        self.opt_d.zero_grad(set_to_none=True)
        l_d.backward()
        self.opt_d.step()

        metrics = {"disc": l_d.item()}
        if step >= tc.disc_warmup_steps:  # generator frozen while the fresh discriminators warm up
            audio_hat = self.generate(mel)
            _, g_mp, f_r_mp, f_g_mp = self.mpd(y=audio, y_hat=audio_hat)
            _, g_mr, f_r_mr, f_g_mr = self.mrd(y=audio, y_hat=audio_hat)
            lg_mp, lst_mp = self.gen_loss(disc_outputs=g_mp)
            lg_mr, lst_mr = self.gen_loss(disc_outputs=g_mr)
            l_fm = self.fm_loss(fmap_r=f_r_mp, fmap_g=f_g_mp) / len(f_r_mp) + \
                tc.mrd_loss_coeff * self.fm_loss(fmap_r=f_r_mr, fmap_g=f_g_mr) / len(f_r_mr)
            l_mel = self.mel_loss(audio_hat, audio)
            l_g = lg_mp / len(lst_mp) + tc.mrd_loss_coeff * lg_mr / len(lst_mr) + l_fm + tc.mel_loss_coeff * l_mel
            self.opt_g.zero_grad(set_to_none=True)
            l_g.backward()
            torch.nn.utils.clip_grad_norm_(self.gen_params, tc.grad_clip)
            self.opt_g.step()
            metrics.update(gen=l_g.item(), mel=l_mel.item(), fm=l_fm.item())
        return metrics

    def state_dict(self) -> dict:
        return dict(vocos=self.vocos.state_dict(), mpd=self.mpd.state_dict(), mrd=self.mrd.state_dict(),
                    opt_g=self.opt_g.state_dict(), opt_d=self.opt_d.state_dict())

    def load_state_dict(self, ck: dict) -> None:
        for k in ("vocos", "mpd", "mrd", "opt_g", "opt_d"):
            getattr(self, k).load_state_dict(ck[k])

    def export(self, path: Path, step: int) -> None:
        save_checkpoint(path, vocos=self.vocos.state_dict(), init=self.cfg.vocoder.init, step=step, mel=self.mel,
                        head_padding=self.vocos.head.istft.padding)


class BigVGANGAN:
    """BigVGAN-v2 generator (weight norm kept for training) + MPD + multi-scale sub-band CQT discriminator, LSGAN +
    feature matching + multi-scale mel L1, AdamW (0.8, 0.99), per-step exponential LR decay (official ``train.py``)."""

    backend, export_name = "bigvgan", "bigvgan_ft.pt"

    def __init__(self, cfg, device):
        self.cfg, vc, tc = cfg, cfg.vocoder, cfg.train
        self.repo = vc.get("repo", BIGVGAN_REPO)
        self.gen = build_bigvgan(self.repo, vc.get("hparams"), pretrained=vc.get("pretrained", True)).to(device)
        if tc.get("compile", False):  # fuse the anti-aliased snake activations: less memory, fewer kernel launches
            for m in self.gen.modules():
                if type(m).__name__ == "Activation1d":
                    m.compile()
        h = self.gen.h
        self.mpd = bd.MultiPeriodDiscriminator(h).to(device)
        cqt = h.get("use_cqtd_instead_of_mrd", False) or h.get("discriminator") != "mrd"
        # stored as "mrd" in the released checkpoints: the sub-band CQT discriminator (v2) or the MRD (v1, base)
        self.mrd = (bd.MultiScaleSubbandCQTDiscriminator(h) if cqt else bd.MultiResolutionDiscriminator(h)).to(device)
        betas = tuple(tc.get("betas", (h["adam_b1"], h["adam_b2"])))
        self.opt_g = torch.optim.AdamW(self.gen.parameters(), tc.lr, betas=betas)
        # same parameter order as the reference (CQT-D first), so its optimizer state can be loaded
        self.d_params = list(itertools.chain(self.mrd.parameters(), self.mpd.parameters()))
        self.opt_d = torch.optim.AdamW(self.d_params, tc.lr, betas=betas)
        if vc.get("pretrained_discriminators", True):
            self._load_released(vc.get("pretrained_optimizer", True))
        self.sched_g, self.sched_d = (torch.optim.lr_scheduler.ExponentialLR(o, tc.get("lr_decay", 1.0))
                                      for o in (self.opt_g, self.opt_d))
        self.mel_loss = bd.MultiScaleMelLoss(SAMPLE_RATE).to(device)
        bf16 = tc.get("bf16_disc", False)
        self.amp = lambda: torch.autocast(device.split(":")[0], torch.bfloat16) if bf16 else nullcontext()
        self.n_gen, self.n_disc = count_params(self.gen), count_params(self.mpd) + count_params(self.mrd)

    def _load_released(self, optimizer: bool) -> None:
        from huggingface_hub import hf_hub_download

        ck = torch.load(hf_hub_download(self.repo, "bigvgan_discriminator_optimizer.pt"), map_location="cpu",
                        weights_only=False)
        self.mpd.load_state_dict(ck["mpd"])
        self.mrd.load_state_dict(ck["mrd"])
        if optimizer:  # AdamW moments of the 5M-step run; the learning rate is ours
            for opt, key in ((self.opt_g, "optim_g"), (self.opt_d, "optim_d")):
                hp = {k: v for k, v in opt.param_groups[0].items() if k != "params"}
                opt.load_state_dict(ck[key])
                for g in opt.param_groups:
                    g.pop("initial_lr", None)
                    g.update(hp)
                for p in opt.param_groups[0]["params"]:
                    assert opt.state[p]["exp_avg"].shape == p.shape, "optimizer state does not match the model"
        print(f"loaded the released discriminators{' and optimizer states' if optimizer else ''} "
              f"(step {ck['steps']})", flush=True)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:
        """Full utterances (samples): eager, so variable lengths do not trigger recompilation."""
        with torch.compiler.set_stance("force_eager") if self.cfg.train.get("compile") else nullcontext():
            return self.gen(mel)[:, 0]

    def step(self, mel: torch.Tensor, audio: torch.Tensor, step: int) -> dict:
        tc = self.cfg.train
        y, y_hat = audio[:, None], self.gen(mel)  # generator in fp32: snake activations need the precision
        with self.amp():
            r_p, g_p, _, _ = self.mpd(y, y_hat.detach())
            r_c, g_c, _, _ = self.mrd(y, y_hat.detach())
        l_d_p, l_d_c = bd.discriminator_loss(r_p, g_p), bd.discriminator_loss(r_c, g_c)
        self.opt_d.zero_grad(set_to_none=True)
        (l_d_p + l_d_c).backward()
        gn_p = torch.nn.utils.clip_grad_norm_(self.mpd.parameters(), tc.grad_clip)
        gn_c = torch.nn.utils.clip_grad_norm_(self.mrd.parameters(), tc.grad_clip)
        self.opt_d.step()

        metrics = {"disc_mpd": l_d_p.item(), "disc_cqtd": l_d_c.item(), "grad_mpd": gn_p.item(),
                   "grad_cqtd": gn_c.item()}
        if step >= tc.disc_warmup_steps:
            l_mel = self.mel_loss(y_hat, y)
            with self.amp():
                _, g_p, f_r_p, f_g_p = self.mpd(y, y_hat)
                _, g_c, f_r_c, f_g_c = self.mrd(y, y_hat)
            l_adv = bd.generator_loss(g_p) + bd.generator_loss(g_c)
            l_fm = bd.feature_loss(f_r_p, f_g_p) + bd.feature_loss(f_r_c, f_g_c)
            l_g = l_adv + l_fm + tc.mel_loss_coeff * l_mel
            self.opt_g.zero_grad(set_to_none=True)
            l_g.backward()
            gn_g = torch.nn.utils.clip_grad_norm_(self.gen.parameters(), tc.grad_clip)
            self.opt_g.step()
            metrics.update(gen=l_g.item(), adv=l_adv.item(), fm=l_fm.item(), mel=l_mel.item(), grad_gen=gn_g.item())
        self.sched_g.step()
        self.sched_d.step()
        metrics["lr"] = self.sched_g.get_last_lr()[0]
        return metrics

    def state_dict(self) -> dict:
        return dict(generator=self.gen.state_dict(), mpd=self.mpd.state_dict(), mrd=self.mrd.state_dict(),
                    opt_g=self.opt_g.state_dict(), opt_d=self.opt_d.state_dict(), sched_g=self.sched_g.state_dict(),
                    sched_d=self.sched_d.state_dict())

    def load_state_dict(self, ck: dict) -> None:
        self.gen.load_state_dict(ck["generator"])
        for k in ("mpd", "mrd", "opt_g", "opt_d", "sched_g", "sched_d"):
            getattr(self, k).load_state_dict(ck[k])

    def export(self, path: Path, step: int) -> None:
        """Same layout as the released ``bigvgan_generator.pt`` (weight norm kept) + the hparams to rebuild it."""
        h = {k: v for k, v in self.gen.h.items() if k != "use_cuda_kernel"}
        save_checkpoint(path, generator=self.gen.state_dict(), hparams=h, repo=self.repo, step=step)


class DriftVocoder:
    """A vocoder trained without a discriminator (``vocoder.objective: drift``, ``drift_vocoder.py``).

    ``S = drift.samples`` waveforms ``G(mel, z)`` per mel segment, ``z`` Gaussian noise channels at the frame rate, are
    drifted towards the real segment in a frozen feature space (``features``), plus ``mel_loss_coeff`` x the multi-scale
    mel L1 of every sample. ``vocoder.arch``: Vocos (pretrained ``vocoder.init``; ``same`` ISTFT padding on bigvgan
    mels) or a BigVGAN generator (``vocoder.repo``). AdamW, per-step exponential LR decay, one clipped gradient.
    ``generate`` and the export run at ``z = 0``, so the exported vocoder is deterministic and streams like a GAN one.
    """

    disc_label = "frozen feature nets"

    def __init__(self, cfg, device, mel: str = "bigvgan", arch: str = "vocos"):
        from .drift_vocoder import PAIRINGS, NoisyVocoder, build_feature_space

        self.cfg, vc, tc, dc = cfg, cfg.vocoder, cfg.train, cfg.drift
        self.mel, self.backend = mel, arch
        self.export_name = "vocos_ft.pt" if arch == "vocos" else "bigvgan_ft.pt"
        if arch == "vocos":
            net = build_vocos(vc.init)
            if mel == "bigvgan":  # F frames <-> F * hop samples, frame i centred on i * hop + hop / 2
                net.head.istft.padding = "same"
        else:
            self.repo = vc.get("repo", BIGVGAN_REPO)
            net = build_bigvgan(self.repo, vc.get("hparams"), pretrained=vc.get("pretrained", True))
            if tc.get("compile", False):
                for m in net.modules():
                    if type(m).__name__ == "Activation1d":
                        m.compile()
        self.gen = NoisyVocoder(net, vc.get("noise_channels", 8)).to(device).train()
        self.features = build_feature_space(cfg.features).to(device)
        self.mel_loss = bd.MultiScaleMelLoss(SAMPLE_RATE).to(device)
        self.pairing = {k: float(w) for k, w in dc.get("pairing", {"conditional": 1.0}).items()}
        mode = dc.get("mode", "official")
        if mode not in ("official", "kyutai"):
            raise ValueError(f"drift.mode must be official or kyutai, got {mode!r}")
        self.taus = None
        groups = [{"params": list(self.gen.parameters())}]
        if mode == "kyutai":  # one learned temperature per pairing, no weight decay (as in train.py)
            init = float(dc.get("kyutai", {}).get("tau_init", 1.0))
            self.taus = torch.nn.ParameterDict({k: torch.nn.Parameter(torch.tensor(init, device=device))
                                                for k in PAIRINGS if self.pairing.get(k)})
            groups.append({"params": list(self.taus.parameters()), "weight_decay": 0.0})
        self.opt = torch.optim.AdamW(groups, tc.lr, betas=tuple(tc.get("betas", (0.8, 0.99))))
        self.sched = torch.optim.lr_scheduler.ExponentialLR(self.opt, tc.get("lr_decay", 1.0))
        self.n_gen, self.n_disc = count_params(self.gen), count_params(self.features)
        # cuDNN autotuning over the ~50 frozen conv shapes: a 12 GB workspace spike and a slower step (RTX 5090)
        self.cudnn_benchmark = tc.get("cudnn_benchmark", False)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:
        """``z = 0`` (the exported vocoder); eager, so variable lengths do not trigger recompilation."""
        with torch.compiler.set_stance("force_eager") if self.cfg.train.get("compile") else nullcontext():
            return self.gen(mel)

    def drift_grad(self, wave: torch.Tensor, audio: torch.Tensor, B: int) -> tuple[torch.Tensor, torch.Tensor, dict]:
        """Gradient of the drift loss w.r.t. the waveforms ``[B * S, n]`` (and the temperatures' ``.grad``), one
        feature-space part at a time: only one part's graph is alive. Returns the gradient, the loss and its info."""
        from .drift_vocoder import map_weight_sum, shifted_views, split_samples, vocoder_drift_loss

        dc = self.cfg.drift
        reduce, kw = dc.get("reduce", "mean"), dc.get("key_weights")
        x = wave.detach().requires_grad_()
        with torch.no_grad():
            views = shifted_views(audio, dc.get("pos_shifts") or ()).flatten(0, 1)
        total, weights, info = 0.0, 0.0, {}
        for part in self.features.parts():
            with torch.no_grad():
                pos = split_samples(part(views), B)
            gen = split_samples(part(x), B)
            loss, inf = vocoder_drift_loss(gen, pos, self.pairing, dc.get("temperatures", (0.02, 0.05, 0.2)), kw,
                                           "sum", dc.get("max_locations"), dc.get("pooled_locations", 128),
                                           self.taus, dc.get("affinity_floor", 1e-6))
            loss.backward()
            total, weights = total + loss.detach(), weights + map_weight_sum(gen, kw)
            for k, v in inf.items():  # per-map stats; the temperature losses (one per pairing) add up over the parts
                info[k] = info[k] + v if k.endswith("tau_loss") and k in info else v
        norm = weights if reduce == "mean" else 1.0
        for t in [] if self.taus is None else self.taus.values():
            t.grad = t.grad * self.cfg.train.drift_coeff / norm
        info.update({k: v / norm for k, v in info.items() if k.endswith("tau_loss")})
        return x.grad / norm, total / norm, info

    def step(self, mel: torch.Tensor, audio: torch.Tensor, step: int) -> dict:
        from .drift_vocoder import summarize

        tc, dc = self.cfg.train, self.cfg.drift
        B, S = mel.shape[0], dc.samples
        z = torch.randn(B * S, self.gen.noise_channels, mel.shape[-1], device=mel.device)
        wave = self.gen(mel.repeat_interleave(S, 0), z)  # [B * S, n], segment-major
        n = min(wave.shape[-1], audio.shape[-1])
        wave, audio = wave[:, :n], audio[:, :n]
        self.opt.zero_grad(set_to_none=True)
        grad, l_drift, info = self.drift_grad(wave, audio, B)
        with nullcontext() if tc.mel_loss_coeff > 0 else torch.no_grad():
            l_mel = self.mel_loss(wave, audio.repeat_interleave(S, 0))
        # d/dwave of drift_coeff * drift loss is drift_coeff * grad: one backward through the generator
        surrogate = tc.drift_coeff * (wave * grad).sum() + (tc.mel_loss_coeff * l_mel if tc.mel_loss_coeff > 0 else 0)
        surrogate.backward()
        loss = tc.drift_coeff * l_drift + tc.mel_loss_coeff * l_mel.detach()
        gn = torch.nn.utils.clip_grad_norm_(self.gen.parameters(), tc.grad_clip)
        self.opt.step()
        self.sched.step()
        with torch.no_grad():  # across-sample std of the log-mel: 0 = the noise is ignored (collapse)
            lm = self.mel_loss.log_mel(wave.detach().float(), 1024)
            spread = lm.view(B, S, *lm.shape[1:]).std(1).mean()
        metrics = {"loss": loss.item(), "drift": l_drift.item(), "mel": l_mel.item(), "spread": spread.item(),
                   "grad": gn.item(), "lr": self.sched.get_last_lr()[0]}
        metrics.update(summarize(info))
        return metrics

    def state_dict(self) -> dict:
        return dict(generator=self.gen.net.state_dict(), opt=self.opt.state_dict(), sched=self.sched.state_dict(),
                    taus=None if self.taus is None else self.taus.state_dict())

    def load_state_dict(self, ck: dict) -> None:
        self.gen.net.load_state_dict(ck["generator"])
        self.opt.load_state_dict(ck["opt"])
        self.sched.load_state_dict(ck["sched"])
        if self.taus is not None and ck.get("taus"):
            self.taus.load_state_dict(ck["taus"])

    def export(self, path: Path, step: int) -> None:
        """The GAN fine-tunes' layouts (Vocos: ``vocos``, ``init``, ``mel``, ``head_padding``; BigVGAN: ``generator``,
        ``repo``, ``hparams``) plus ``noise_channels``: :class:`~drifting_tts.vocoder.Vocoder` runs it at ``z = 0``."""
        net, k = self.gen.net, self.gen.noise_channels
        if self.backend == "vocos":
            save_checkpoint(path, vocos=net.state_dict(), init=self.cfg.vocoder.init, step=step, mel=self.mel,
                            head_padding=net.head.istft.padding, noise_channels=k, objective="drift")
        else:
            h = {key: v for key, v in net.h.items() if key != "use_cuda_kernel"}
            save_checkpoint(path, generator=net.state_dict(), hparams=h, repo=self.repo, step=step, noise_channels=k,
                            objective="drift")


def build_trainer(cfg, device, arch: str, mel: str):
    """``vocoder.objective``: ``gan`` (default: :class:`VocosGAN` / :class:`BigVGANGAN`) or ``drift``."""
    objective = cfg.vocoder.get("objective", "gan")
    if objective not in OBJECTIVES:
        raise ValueError(f"vocoder.objective must be one of {OBJECTIVES}, got {objective!r}")
    if objective == "drift":
        return DriftVocoder(cfg, device, mel=mel, arch=arch)
    return BigVGANGAN(cfg, device) if arch == "bigvgan" else VocosGAN(cfg, device, mel=mel)


@torch.no_grad()
def log_samples(gan, tts, batch: dict, stats: dict, tc, writer, step: int, device) -> None:
    """Full validation utterances: the vocoder on GTA mels and on recorded mels, plus the real audio."""
    gta = gta_mels(tts, batch, tc.gta_temperature, device) * stats["std"] + stats["mean"]
    rec = batch["mel"].to(device) * stats["std"] + stats["mean"]
    for i, n in enumerate(batch["mel_len"].tolist()):
        for name, mel in (("gta", gta), ("recorded_mel", rec)):
            wav = gan.generate(mel[i: i + 1, :, :n])[0].clamp(-1, 1).float().cpu()
            writer.add_audio(f"{name}/{i}", wav, step, sample_rate=SAMPLE_RATE)
        writer.add_audio(f"real/{i}", batch["audio"][i, : segment_samples(n, getattr(gan, "mel", gan.backend))], step,
                         sample_rate=SAMPLE_RATE)


def run(args) -> None:
    from torch.utils.tensorboard import SummaryWriter

    from .train import load_tts

    cfg = load_config(args.config, args.overrides)
    work = Path(args.workdir)
    work.mkdir(parents=True, exist_ok=True)
    save_config(cfg, work / "config.yaml")
    tc = cfg.train
    seed_everything(tc.seed)
    device = "cuda" if torch.cuda.is_available() and not tc.get("cpu", False) else "cpu"

    tts, tts_cfg, stats = load_tts(cfg.tts.path, device)
    backend = stats.get("backend", "vocos")  # the mel type the TTS model was trained on
    if cfg.vocoder.get("backend", backend) != backend:
        raise ValueError(f"config asks for {cfg.vocoder.backend} mels but the TTS model was trained on "
                         f"{backend} mels (`prepare --backend`)")
    arch = cfg.vocoder.get("arch", backend)  # the vocoder architecture: a Vocos can also learn BigVGAN mels
    if arch == "bigvgan" and backend != "bigvgan":
        raise ValueError("a BigVGAN vocoder needs a TTS model trained on bigvgan mels")
    tts.requires_grad_(False)
    d = cfg.data
    ds = MelDataset(d.root, "train", min_quality=d.min_quality, min_frames=tc.segment_frames, max_frames=d.max_frames,
                    with_audio=True, with_f0=tts.pitch_enabled, filters=d.get("filters"))
    sampler = BucketBatchSampler([ds.frames(i) for i in range(len(ds))], max_frames=tc.batch_frames,
                                 max_batch=tc.batch_size, seed=tc.seed)
    loader = DataLoader(ds, batch_sampler=sampler, collate_fn=collate, num_workers=tc.num_workers,
                        pin_memory=True, persistent_workers=tc.num_workers > 0)

    gan = build_trainer(cfg, device, arch, backend)
    print(f"{arch} vocoder on {backend} mels {gan.n_gen:.1f}M, {getattr(gan, 'disc_label', 'discriminators')} "
          f"{gan.n_disc:.1f}M, {len(ds)} utterances", flush=True)
    writer = SummaryWriter(work / "tb")
    samples = None
    if tc.get("sample_every", 0) > 0:
        val = MelDataset(d.root, "val", min_frames=tc.segment_frames, max_frames=d.max_frames, with_audio=True,
                         with_f0=tts.pitch_enabled)
        val = val if len(val) else ds
        samples = collate([val[i] for i in range(min(tc.get("num_samples", 2), len(val)))])

    step = 0
    if (work / "last.pt").exists():
        ck = torch.load(work / "last.pt", map_location="cpu", weights_only=False)
        gan.load_state_dict(ck)
        step = ck["step"]
        sampler.epoch = ck.get("epoch", 0)
        print(f"resumed from step {step}", flush=True)

    it = infinite(loader)
    t0, agg = time.time(), {}
    while step < tc.steps:
        batch = next(it)
        use_gta = torch.rand(()) < tc.gta_prob
        mel = gta_mels(tts, batch, tc.gta_temperature, device) if use_gta else batch["mel"].to(device)
        mel = mel * stats["std"] + stats["mean"]  # back to log-mel, the vocoder's input
        mel, audio = random_segments(mel, batch["audio"].to(device), batch["mel_len"], tc.segment_frames, backend)
        # fixed segment shapes: faster convolutions (GAN; the drift trainer opts out, see DriftVocoder)
        with torch.backends.cudnn.flags(enabled=True, benchmark=getattr(gan, "cudnn_benchmark", True)):
            metrics = gan.step(mel, audio, step)
        step += 1
        for k, v in metrics.items():
            agg[k] = agg.get(k, 0.0) + v
        if step % tc.log_every == 0:
            n = tc.log_every
            for k, v in agg.items():
                writer.add_scalar(f"vocoder/{k}", v / n, step)
            rate = n / (time.time() - t0)
            mem = f", {torch.cuda.max_memory_allocated() / 2**30:.1f} GB" if device == "cuda" else ""
            print(f"step {step} " + " ".join(f"{k}={v / n:.4g}" for k, v in agg.items()) + f" ({rate:.2f} it/s{mem})",
                  flush=True)
            t0, agg = time.time(), {}
        if samples is not None and step % tc.sample_every == 0:
            log_samples(gan, tts, samples, stats, tc, writer, step, device)
        if step % tc.save_every == 0 or step == tc.steps:
            save_checkpoint(work / "last.pt", step=step, epoch=sampler.epoch, **gan.state_dict())
            gan.export(work / gan.export_name, step)
    print(f"done: {work / gan.export_name}", flush=True)
