"""Fine-tune the vocoder (Vocos or BigVGAN-v2) on mels generated by the trained TTS model ("GTA" fine-tuning).

The frozen TTS model produces mels for training utterances under the *ground-truth* alignment
(teacher-forced durations), so every generated frame lines up with the recorded waveform. The
vocoder is then trained to turn the model's (smoother) mels into the real audio with its original
GAN objective:

- ``vocos``: fresh multi-period and multi-resolution discriminators (none were released), hinge
  loss, feature matching and an L1 log-mel loss, after a discriminator warm-up. A Vocos vocoder can also be
  trained on BigVGAN mels (``vocoder.arch: vocos`` with a BigVGAN-mel TTS model): its ISTFT head then uses
  ``same`` padding, which centres frame ``i`` on sample ``i * hop + hop / 2`` as BigVGAN's uncentred STFT does.
- ``bigvgan``: resumes NVIDIA's released generator *and* discriminators (MPD + multi-scale sub-band
  CQT) with their AdamW states, as the official recipe does; LSGAN, feature matching and the
  multi-scale mel L1 (x15), at the learning rate where the released schedule ended.
- ``vae_decoder`` (a TTS model trained on VAE latents, ``extract-latents``; VoxCPM2, DAC-VAE): the VAE's decoder in
  place of the vocoder, trained on generated latents with the ``bigvgan`` recipe and NVIDIA's released 24 kHz
  discriminators (:class:`VAEDecoderGAN`). DAC-VAE's watermark stays frozen and is added as at release. Exports
  ``decoder_ft.pt`` for ``LatentVocoder`` / ``Synthesizer(vocoder=...)``.

``vocoder.objective: drift`` trains either architecture without a GAN (:class:`DriftVocoder`, ``drift_vocoder.py``).
"""

from __future__ import annotations

import argparse
import itertools
import math
import shutil
import time
from contextlib import nullcontext
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader

from .alignment import sequence_mask
from .audio import HOP_LENGTH, SAMPLE_RATE
from .config import load_config, save_config
from .data import BucketBatchSampler, MelDataset, MelStats, collate
from .models import bigvgan_disc as bd
from .models.text_encoder import align, token_pitch
from .utils import count_params, infinite, save_checkpoint, seed_everything
from .vocoder import BIGVGAN_REPO, build_bigvgan, build_vocos

OBJECTIVES = ("gan", "drift")


def add_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--config", default="configs/vocoder.yaml")
    p.add_argument("--workdir", default="runs/vocoder")
    p.add_argument("overrides", nargs="*", help="config overrides, e.g. train.steps=1000")


@torch.no_grad()
def gta_mels(tts, batch: dict, temperature: float, device, cfg_scale: float = 1.0, steps: int | None = None,
             generator: torch.Generator | None = None) -> torch.Tensor:
    """Teacher-forced (ground-truth alignment) generated mels ``[B, n_mels, T]`` (normalised), or latent frames for a
    model trained on VAE latents.

    Pitch-conditioned models use the ground-truth pitch from ``batch["f0"]``, or the predicted pitch without it."""
    text, text_len = batch["text"].to(device), batch["text_len"].to(device)
    y, y_len, spk = batch["mel"].to(device), batch["mel_len"].to(device), batch["spk"].to(device)
    y_mask = sequence_mask(y_len, y.shape[-1])
    h, mu, _, x_mask = tts.encoder(text, text_len, spk)
    attn, _ = align(mu, x_mask, y, y_mask[:, None].float())
    if tts.pitch_enabled:
        lf0_mean, lf0_std = tts.lf0_stats.tolist()
        pitch = token_pitch(batch["f0"].to(device), attn, lf0_mean, lf0_std) if "f0" in batch else None
        h, _ = tts.pitch_condition(h, x_mask, spk, pitch)
    cond = tts.frame_condition(h, mu, attn)
    z = torch.randn(y.shape[0], y.shape[1], y.shape[-1], device=device, generator=generator) * temperature
    alpha = torch.full((y.shape[0],), float(cfg_scale), device=device)
    steps = tts.generator.num_steps if steps is None else steps
    return tts.rollout(z, cond, spk, alpha, steps, generator=generator, mask=y_mask) * y_mask[:, None]


def segment_samples(frames: int, backend: str = "vocos") -> int:
    """Waveform samples produced from ``frames`` mel frames. Vocos (centred STFT, ISTFT head): frame ``i`` is centred
    on sample ``i * hop``, so ``F`` frames <-> ``(F - 1) * hop`` samples. BigVGAN (reflect-padded uncentred STFT,
    256x upsampler): frame ``i`` is centred on ``i * hop + hop / 2``, so ``F`` frames <-> ``F * hop`` samples."""
    return (frames - 1) * HOP_LENGTH if backend == "vocos" else frames * HOP_LENGTH


def random_segments(mel: torch.Tensor, audio: torch.Tensor, mel_len: torch.Tensor, frames: int,
                    backend: str = "vocos"):
    """Aligned random windows: mel frames ``[s, s + frames)`` <-> samples ``[s * hop, s * hop + n)``."""
    B = mel.shape[0]
    starts = (torch.rand(B) * (mel_len.cpu() - frames + 1).clamp_min(1).float()).long()
    n = segment_samples(frames, backend)
    m = torch.stack([mel[i, :, s: s + frames] for i, s in enumerate(starts.tolist())])
    a = torch.stack([audio[i, s * HOP_LENGTH: s * HOP_LENGTH + n] for i, s in enumerate(starts.tolist())])
    return m, a


class VocosGAN:
    """Vocos generator + fresh MPD / MRD: hinge + feature matching + 45 x log-mel L1 (the Vocos recipe).

    Opt-in extensions (the defaults keep the recipe):

    - ``vocoder.discriminators``: which of Vocos's discriminators to train (default ``[mpd, mrd]``; ``[]`` for none).
    - ``vocoder.bigvgan_discriminators``: NVIDIA's BigVGAN-v2 discriminators next to them (``mpd``, ``cqtd``: the
      multi-scale sub-band CQT discriminator), with the released weights (``vocoder.bigvgan_pretrained``, default
      true) and, when both are used, the AdamW moments of the released 5M-step run. They keep their LSGAN loss,
      weighted ``train.bigvgan_loss_coeff``: averaged over sub-discriminators like the Vocos terms
      (``train.bigvgan_reduce: mean``) or summed with feature matching x 2 as in BigVGAN (``sum``).
    - Loss balance: ``train.mel_loss: multiscale`` (BigVGAN-v2's 7-scale log10-mel L1 instead of Vocos's single
      100-band one), ``train.fm_loss_coeff`` (Vocos feature matching), ``train.mrd_loss_coeff``.
    - Learning rates: ``train.lr`` (generator), ``train.lr_disc`` (discriminators, default ``lr``), a linear generator
      warm-up over ``train.warmup_steps``; ``train.lr_schedule: cosine`` decays every rate to ``train.lr_min_ratio``
      of its peak over ``train.steps``.
    - ``train.init_from``: start from another fine-tune's ``last.pt`` at step 0 (the generator, the discriminators it
      has and, for an unchanged set, their optimizer states), used when this run has no ``last.pt`` of its own.
    - ``train.iaf_loss_coeff``: :func:`phase_derivative_loss` against the recording (instantaneous frequency, which a
      time shift of the output does not change), on recorded-mel batches, or on every batch with
      ``train.iaf_on_gta``.
    - ``train.gta_mel_loss_coeff``: the mel weight on generated-mel batches (default ``mel_loss_coeff``), whose
      mels do not determine the recording's detail.
    """

    batch_is_gta = True  # set by ``run`` before each step: whether the batch holds generated mels

    backend, export_name = "vocos", "vocos_ft.pt"
    VOCOS_DISCS, BIGVGAN_DISCS = ("mpd", "mrd"), ("mpd", "cqtd")

    def __init__(self, cfg, device, mel: str = "vocos"):
        from vocos.discriminators import MultiPeriodDiscriminator, MultiResolutionDiscriminator
        from vocos.loss import DiscriminatorLoss, FeatureMatchingLoss, GeneratorLoss, MelSpecReconstructionLoss

        self.cfg, vc, tc, self.mel = cfg, cfg.vocoder, cfg.train, mel
        self.vocos = build_vocos(vc.init).to(device).train()
        if mel == "bigvgan":  # F frames <-> F * hop samples, frame i centred on i * hop + hop / 2
            self.vocos.head.istft.padding = "same"
        kinds, bkinds = list(vc.get("discriminators", self.VOCOS_DISCS)), list(vc.get("bigvgan_discriminators") or [])
        for k, allowed in ((kinds, self.VOCOS_DISCS), (bkinds, self.BIGVGAN_DISCS)):
            if set(k) - set(allowed):
                raise ValueError(f"unknown discriminators {sorted(set(k) - set(allowed))}, expected {allowed}")
        if not kinds and not bkinds:
            raise ValueError("VocosGAN needs at least one discriminator")
        self.mpd = MultiPeriodDiscriminator().to(device) if "mpd" in kinds else None
        self.mrd = MultiResolutionDiscriminator().to(device) if "mrd" in kinds else None
        self.gen_params = list(self.vocos.backbone.parameters()) + list(self.vocos.head.parameters())
        self.opt_g = torch.optim.AdamW(self.gen_params, lr=tc.lr, betas=(0.8, 0.9))
        d_params = [p for d in (self.mpd, self.mrd) if d is not None for p in d.parameters()]
        self.opt_d = torch.optim.AdamW(d_params, lr=tc.get("lr_disc", tc.lr), betas=(0.8, 0.9)) if d_params else None
        self.bigvgan = self._bigvgan_discriminators(bkinds, device) if bkinds else {}
        self.disc_loss, self.gen_loss, self.fm_loss = DiscriminatorLoss(), GeneratorLoss(), FeatureMatchingLoss()
        mel_loss = tc.get("mel_loss", "single")
        if mel_loss not in ("single", "multiscale"):
            raise ValueError(f"train.mel_loss must be single or multiscale, got {mel_loss!r}")
        self.mel_loss = (MelSpecReconstructionLoss(sample_rate=SAMPLE_RATE) if mel_loss == "single" else
                         bd.MultiScaleMelLoss(SAMPLE_RATE)).to(device)
        if tc.get("bigvgan_reduce", "mean") not in ("mean", "sum"):
            raise ValueError(f"train.bigvgan_reduce must be mean or sum, got {tc.bigvgan_reduce!r}")
        self.scheds = [self._schedule(o, i == 0) for i, o in enumerate(self.optimizers())]
        self.n_gen = count_params(self.vocos)
        self.n_disc = sum(count_params(d) for d in (self.mpd, self.mrd, *self.bigvgan.values()) if d is not None)

    def optimizers(self) -> list:
        return [o for o in (self.opt_g, self.opt_d, getattr(self, "opt_db", None)) if o is not None]

    def _schedule(self, opt, generator: bool):
        """Factor on the peak learning rate at step ``s``: linear warm-up (generator), then constant or cosine."""
        tc = self.cfg.train
        kind, floor, steps = tc.get("lr_schedule", "constant"), tc.get("lr_min_ratio", 0.0), tc.steps
        warmup = tc.get("warmup_steps", 0) if generator else 0
        if kind not in ("constant", "cosine"):
            raise ValueError(f"train.lr_schedule must be constant or cosine, got {kind!r}")

        def factor(s: int) -> float:
            decay = 1.0 if kind == "constant" else floor + (1 - floor) * 0.5 * (1 + math.cos(math.pi * min(s, steps)
                                                                                           / steps))
            return decay * min(1.0, (s + 1) / warmup) if warmup else decay

        return torch.optim.lr_scheduler.LambdaLR(opt, factor)

    def _bigvgan_discriminators(self, kinds: list[str], device) -> dict:
        """NVIDIA's BigVGAN-v2 MPD / CQT-D (released weights unless ``vocoder.bigvgan_pretrained: false``) and their
        optimizer ``opt_db`` (AdamW (0.8, 0.99); the released moments when both are used)."""
        vc, tc = self.cfg.vocoder, self.cfg.train
        repo = vc.get("bigvgan_repo", BIGVGAN_REPO)
        h = discriminator_hparams(repo, vc.get("bigvgan_hparams"))  # overrides: e.g. smaller test models
        discs = {}
        if "cqtd" in kinds:  # the released optimizer's parameter order: CQT-D first
            discs["cqtd"] = bd.MultiScaleSubbandCQTDiscriminator(h).to(device)
        if "mpd" in kinds:
            discs["mpd"] = bd.MultiPeriodDiscriminator(h).to(device)
        params = [p for d in discs.values() for p in d.parameters()]
        self.opt_db = torch.optim.AdamW(params, tc.get("lr_disc", tc.lr),
                                        betas=tuple(tc.get("bigvgan_betas", (h["adam_b1"], h["adam_b2"]))))
        if vc.get("bigvgan_pretrained", True):
            from huggingface_hub import hf_hub_download

            ck = torch.load(hf_hub_download(repo, "bigvgan_discriminator_optimizer.pt"), map_location="cpu",
                            weights_only=False)
            for k, d in discs.items():
                d.load_state_dict(ck["mrd" if k == "cqtd" else "mpd"])  # stored as "mrd" in the released file
            if len(discs) == 2:
                _load_optimizer(self.opt_db, ck["optim_d"])
            print(f"BigVGAN discriminators {list(discs)}: released weights (step {ck['steps']})"
                  f"{' and AdamW moments' if len(discs) == 2 else ''}", flush=True)
        return discs

    def segments(self, mel: torch.Tensor, audio: torch.Tensor, mel_len: torch.Tensor):
        return random_segments(mel, audio, mel_len, self.cfg.train.segment_frames, self.mel)

    def audio_samples(self, frames: int) -> int:
        return segment_samples(frames, self.mel)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:  # Vocos.decode runs under inference_mode
        return self.vocos.head(self.vocos.backbone(mel))

    def _vocos_terms(self, audio: torch.Tensor, audio_hat: torch.Tensor):
        """``(weight, disc outputs)`` of Vocos's discriminators: MPD 1, MRD ``mrd_loss_coeff``."""
        for d, w in ((self.mpd, 1.0), (self.mrd, self.cfg.train.mrd_loss_coeff)):
            if d is not None:
                yield w, d(y=audio, y_hat=audio_hat)

    def _bigvgan_terms(self, audio: torch.Tensor, audio_hat: torch.Tensor):
        for k, d in self.bigvgan.items():
            yield k, d(audio[:, None], audio_hat[:, None])

    def step(self, mel: torch.Tensor, audio: torch.Tensor, step: int) -> dict:
        tc = self.cfg.train
        c_b, c_fm = tc.get("bigvgan_loss_coeff", 1.0), tc.get("fm_loss_coeff", 1.0)
        summed = tc.get("bigvgan_reduce", "mean") == "sum"
        with torch.no_grad():
            audio_hat = self.generate(mel)
        l_d, l_db, metrics = 0.0, 0.0, {}
        for w, (r, g, _, _) in self._vocos_terms(audio, audio_hat):
            loss, losses_r, _ = self.disc_loss(disc_real_outputs=r, disc_generated_outputs=g)
            l_d = l_d + w * loss / len(losses_r)
        for k, (r, g, _, _) in self._bigvgan_terms(audio, audio_hat):
            loss = bd.discriminator_loss(r, g) / (1 if summed else len(r))
            metrics[f"disc_bigvgan_{k}"] = loss.item()
            l_db = l_db + loss
        for opt in self.optimizers()[1:]:
            opt.zero_grad(set_to_none=True)
        (l_d + l_db).backward()
        for opt in self.optimizers()[1:]:
            opt.step()
        if self.opt_d is not None:
            metrics["disc"] = l_d.item()

        if step >= tc.disc_warmup_steps:  # generator frozen while the fresh discriminators warm up
            audio_hat = self.generate(mel)
            l_mel = self.mel_loss(audio_hat, audio)
            c_mel = tc.get("gta_mel_loss_coeff", tc.mel_loss_coeff) if self.batch_is_gta else tc.mel_loss_coeff
            l_g, l_fm = c_mel * l_mel, 0.0
            c_iaf = tc.get("iaf_loss_coeff", 0.0)
            if c_iaf > 0 and (tc.get("iaf_on_gta", False) or not self.batch_is_gta):
                l_iaf = phase_derivative_loss(audio_hat, audio)
                l_g = l_g + c_iaf * l_iaf
                metrics["iaf"] = l_iaf.item()
            for w, (_, g, f_r, f_g) in self._vocos_terms(audio, audio_hat):
                adv, adv_k = self.gen_loss(disc_outputs=g)
                fm = self.fm_loss(fmap_r=f_r, fmap_g=f_g) / len(f_r)
                l_g, l_fm = l_g + w * (adv / len(adv_k) + c_fm * fm), l_fm + w * fm.detach()
            for k, (_, g, f_r, f_g) in self._bigvgan_terms(audio, audio_hat):
                if summed:  # BigVGAN: sums over sub-discriminators, feature matching x 2
                    adv, fm = bd.generator_loss(g), bd.feature_loss(f_r, f_g)
                else:  # Vocos's scale: means over sub-discriminators, no factor 2
                    adv, fm = bd.generator_loss(g) / len(g), self.fm_loss(fmap_r=f_r, fmap_g=f_g) / len(f_r)
                l_g = l_g + c_b * (adv + fm)
                metrics.update({f"adv_bigvgan_{k}": adv.item(), f"fm_bigvgan_{k}": fm.item()})
            self.opt_g.zero_grad(set_to_none=True)
            l_g.backward()
            grad = torch.nn.utils.clip_grad_norm_(self.gen_params, tc.grad_clip)
            self.opt_g.step()
            metrics.update(gen=l_g.item(), mel=l_mel.item(), fm=float(l_fm), grad_gen=grad.item())
        for sched in self.scheds:
            sched.step()
        if tc.get("lr_schedule", "constant") != "constant" or tc.get("warmup_steps", 0):
            metrics["lr"] = self.scheds[0].get_last_lr()[0]
        return metrics

    def state_dict(self) -> dict:
        out = dict(vocos=self.vocos.state_dict(), opt_g=self.opt_g.state_dict())
        for k in ("mpd", "mrd", "opt_d", "opt_db"):
            if getattr(self, k, None) is not None:
                out[k] = getattr(self, k).state_dict()
        out.update({f"bigvgan_{k}": d.state_dict() for k, d in self.bigvgan.items()})
        if tc_scheduled(self.cfg.train):
            out["scheds"] = [s.state_dict() for s in self.scheds]
        return out

    def load_state_dict(self, ck: dict) -> None:
        self.vocos.load_state_dict(ck["vocos"])
        self.opt_g.load_state_dict(ck["opt_g"])
        for k in ("mpd", "mrd", "opt_d", "opt_db"):
            if getattr(self, k, None) is not None:
                getattr(self, k).load_state_dict(ck[k])
        for k, d in self.bigvgan.items():
            d.load_state_dict(ck[f"bigvgan_{k}"])
        for s, state in zip(self.scheds, ck.get("scheds", [])):
            s.load_state_dict(state)

    def init_from(self, path: str) -> None:
        """Weights (and optimizer states where the parameter sets match) of a finished run's ``last.pt``; the
        learning rates stay this run's."""
        ck = torch.load(path, map_location="cpu", weights_only=False)
        self.vocos.load_state_dict(ck["vocos"])
        _load_optimizer(self.opt_g, ck["opt_g"])
        loaded = ["generator"]
        for k in ("mpd", "mrd"):
            if getattr(self, k) is not None and k in ck:
                getattr(self, k).load_state_dict(ck[k])
                loaded.append(k)
        same = all((getattr(self, k) is None) == (k not in ck) for k in ("mpd", "mrd"))
        if self.opt_d is not None and same and "opt_d" in ck:
            _load_optimizer(self.opt_d, ck["opt_d"])
            loaded.append("opt_d")
        for k, d in self.bigvgan.items():
            if f"bigvgan_{k}" in ck:
                d.load_state_dict(ck[f"bigvgan_{k}"])
                loaded.append(f"bigvgan_{k}")
        print(f"initialised from {path} (step {ck.get('step')}): {', '.join(loaded)}", flush=True)

    def export(self, path: Path, step: int) -> None:
        save_checkpoint(path, vocos=self.vocos.state_dict(), init=self.cfg.vocoder.init, step=step, mel=self.mel,
                        head_padding=self.vocos.head.istft.padding)


def phase_derivative_loss(y_hat: torch.Tensor, y: torch.Tensor, n_fft: int = 1024, hop: int = 256) -> torch.Tensor:
    """Instantaneous-frequency loss (APNet's IAF term, smooth form): ``1 - cos`` of the difference between the
    frame-to-frame phase advance of ``y_hat`` and of ``y`` in every STFT bin, weighted by the magnitude of ``y``
    (mean weight 1). A constant time shift of ``y_hat`` leaves it unchanged. Phasors are softened by 1e-4 of the peak
    magnitude so that near-silent bins give bounded gradients."""
    window = torch.hann_window(n_fft, device=y.device)
    s_hat, s = (torch.stft(x.float(), n_fft, hop, n_fft, window, return_complex=True) for x in (y_hat, y))

    def advance(spec: torch.Tensor) -> torch.Tensor:
        mag = spec.abs()
        unit = spec / (mag + 1e-4 * mag.amax(dim=(1, 2), keepdim=True))
        return unit[..., 1:] * unit[..., :-1].conj()

    mag, a, b = s.abs(), advance(s_hat), advance(s)
    w = (mag[..., 1:] * mag[..., :-1]).sqrt()
    w = w / w.mean().clamp_min(1e-8)
    return (w * (a.abs() * b.abs() - (a * b.conj()).real)).mean()  # |a| |b| (1 - cos), 0 for y_hat = y


def tc_scheduled(tc) -> bool:
    """Whether a learning-rate schedule is configured (else the saved state keeps the original layout)."""
    return tc.get("lr_schedule", "constant") != "constant" or bool(tc.get("warmup_steps", 0))


def _load_optimizer(opt, state: dict) -> None:
    """``opt.load_state_dict(state)`` (moments of the same parameters), keeping ``opt``'s hyperparameters."""
    hp = [{k: v for k, v in g.items() if k != "params"} for g in opt.param_groups]
    opt.load_state_dict(state)
    for g, h in zip(opt.param_groups, hp):
        g.pop("initial_lr", None)
        g.update(h)
    for g in opt.param_groups:
        for p in g["params"]:
            if p in opt.state:
                assert opt.state[p]["exp_avg"].shape == p.shape, "optimizer state does not match the model"


class BigVGANGAN:
    """BigVGAN-v2 generator (weight norm kept for training) + MPD + multi-scale sub-band CQT discriminator, LSGAN +
    feature matching + multi-scale mel L1, AdamW (0.8, 0.99), per-step exponential LR decay (official ``train.py``)."""

    backend, export_name = "bigvgan", "bigvgan_ft.pt"
    released_generator = True  # self.gen is the released BigVGAN: its AdamW state is loaded with the discriminators

    def __init__(self, cfg, device):
        self.cfg, vc, tc = cfg, cfg.vocoder, cfg.train
        self.repo = vc.get("repo", BIGVGAN_REPO)
        self.gen = build_bigvgan(self.repo, vc.get("hparams"), pretrained=vc.get("pretrained", True)).to(device)
        if tc.get("compile", False):  # fuse the anti-aliased snake activations: less memory, fewer kernel launches
            for m in self.gen.modules():
                if type(m).__name__ == "Activation1d":
                    m.compile()
        self._setup(self.gen.h, device)

    def _setup(self, h: dict, device) -> None:
        """The discriminators of ``h`` (released weights unless ``vocoder.pretrained_discriminators: false``), the
        optimizers and LR schedules of ``self.gen`` and the discriminators, and the mel loss."""
        vc, tc = self.cfg.vocoder, self.cfg.train
        self.mpd = bd.MultiPeriodDiscriminator(h).to(device)
        cqt = h.get("use_cqtd_instead_of_mrd", False) or h.get("discriminator") != "mrd"
        # stored as "mrd" in the released checkpoints: the sub-band CQT discriminator (v2) or the MRD (v1, base)
        self.mrd = (bd.MultiScaleSubbandCQTDiscriminator(h) if cqt else bd.MultiResolutionDiscriminator(h)).to(device)
        betas = tuple(tc.get("betas", (h["adam_b1"], h["adam_b2"])))
        # frozen generator parameters (a VAE decoder's watermark) are left out
        self.opt_g = torch.optim.AdamW([p for p in self.gen.parameters() if p.requires_grad], tc.lr, betas=betas)
        # same parameter order as the reference (CQT-D first), so its optimizer state can be loaded
        self.d_params = list(itertools.chain(self.mrd.parameters(), self.mpd.parameters()))
        self.opt_d = torch.optim.AdamW(self.d_params, tc.get("lr_d", tc.lr), betas=betas)
        if vc.get("pretrained_discriminators", True):
            self._load_released(vc.get("pretrained_optimizer", True))
        decay, warmup = tc.get("lr_decay", 1.0), tc.get("warmup_steps", 0)
        self.sched_d = torch.optim.lr_scheduler.ExponentialLR(self.opt_d, decay)
        # a fresh generator optimizer (no released state) takes sign-like first steps: warm its learning rate up
        self.sched_g = torch.optim.lr_scheduler.LambdaLR(
            self.opt_g, lambda s: min(1.0, (s + 1) / warmup) * decay**s) if warmup else \
            torch.optim.lr_scheduler.ExponentialLR(self.opt_g, decay)
        self.mel_loss = bd.MultiScaleMelLoss(SAMPLE_RATE).to(device)
        bf16 = tc.get("bf16_disc", False)
        self.amp = lambda: torch.autocast(device.split(":")[0], torch.bfloat16) if bf16 else nullcontext()
        self.n_gen, self.n_disc = count_params(self.gen), count_params(self.mpd) + count_params(self.mrd)

    def _load_released(self, optimizer: bool) -> None:
        from huggingface_hub import hf_hub_download

        ck = torch.load(hf_hub_download(self.repo, "bigvgan_discriminator_optimizer.pt"), map_location="cpu",
                        weights_only=False)
        self.mpd.load_state_dict(ck["mpd"])
        self.mrd.load_state_dict(ck["mrd"])
        if optimizer:  # AdamW moments of the 5M-step run (the generator's only for BigVGAN); the learning rate is ours
            pairs = ((self.opt_g, "optim_g"), (self.opt_d, "optim_d")) if self.released_generator else \
                ((self.opt_d, "optim_d"),)
            for opt, key in pairs:
                hp = {k: v for k, v in opt.param_groups[0].items() if k != "params"}
                opt.load_state_dict(ck[key])
                for g in opt.param_groups:
                    g.pop("initial_lr", None)
                    g.update(hp)
                for p in opt.param_groups[0]["params"]:
                    assert opt.state[p]["exp_avg"].shape == p.shape, "optimizer state does not match the model"
        print(f"loaded the released discriminators{' and optimizer states' if optimizer else ''} "
              f"(step {ck['steps']})", flush=True)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:
        """Full utterances (samples): eager, so variable lengths do not trigger recompilation."""
        with torch.compiler.set_stance("force_eager") if self.cfg.train.get("compile") else nullcontext():
            return self.gen(mel)[:, 0]

    def segments(self, mel: torch.Tensor, audio: torch.Tensor, mel_len: torch.Tensor):
        return random_segments(mel, audio, mel_len, self.cfg.train.segment_frames, "bigvgan")

    def audio_samples(self, frames: int) -> int:
        return segment_samples(frames, "bigvgan")

    def forward(self, x) -> torch.Tensor:
        """Training segments -> ``[B, 1, samples]``."""
        return self.gen(x)

    def step(self, mel, audio: torch.Tensor, step: int) -> dict:
        tc = self.cfg.train
        c_adv, c_fm = tc.get("adv_loss_coeff", 1.0), tc.get("fm_loss_coeff", 1.0)
        gan = c_adv > 0 or c_fm > 0  # both 0: a mel-loss-only fine-tune, the discriminators are not run
        y, y_hat = audio[:, None], self.forward(mel)  # generator in fp32: snake activations need the precision
        metrics = {}
        if gan:
            with self.amp():
                r_p, g_p, _, _ = self.mpd(y, y_hat.detach())
                r_c, g_c, _, _ = self.mrd(y, y_hat.detach())
            l_d_p, l_d_c = bd.discriminator_loss(r_p, g_p), bd.discriminator_loss(r_c, g_c)
            self.opt_d.zero_grad(set_to_none=True)
            (l_d_p + l_d_c).backward()
            gn_p = torch.nn.utils.clip_grad_norm_(self.mpd.parameters(), tc.grad_clip)
            gn_c = torch.nn.utils.clip_grad_norm_(self.mrd.parameters(), tc.grad_clip)
            self.opt_d.step()
            metrics.update(disc_mpd=l_d_p.item(), disc_cqtd=l_d_c.item(), grad_mpd=gn_p.item(), grad_cqtd=gn_c.item())
        if step >= tc.disc_warmup_steps:
            l_mel = self.mel_loss(y_hat, y)
            l_g = tc.mel_loss_coeff * l_mel
            if gan:
                with self.amp():
                    _, g_p, f_r_p, f_g_p = self.mpd(y, y_hat)
                    _, g_c, f_r_c, f_g_c = self.mrd(y, y_hat)
                l_adv = bd.generator_loss(g_p) + bd.generator_loss(g_c)
                l_fm = bd.feature_loss(f_r_p, f_g_p) + bd.feature_loss(f_r_c, f_g_c)
                l_g = l_g + c_adv * l_adv + c_fm * l_fm
                metrics.update(adv=l_adv.item(), fm=l_fm.item())
            self.opt_g.zero_grad(set_to_none=True)
            l_g.backward()
            gn_g = torch.nn.utils.clip_grad_norm_(self.gen.parameters(), tc.grad_clip)
            self.opt_g.step()
            metrics.update(gen=l_g.item(), mel=l_mel.item(), grad_gen=gn_g.item())
        self.sched_g.step()
        self.sched_d.step()
        metrics["lr"] = self.sched_g.get_last_lr()[0]
        return metrics

    def state_dict(self) -> dict:
        return dict(generator=self.gen.state_dict(), mpd=self.mpd.state_dict(), mrd=self.mrd.state_dict(),
                    opt_g=self.opt_g.state_dict(), opt_d=self.opt_d.state_dict(), sched_g=self.sched_g.state_dict(),
                    sched_d=self.sched_d.state_dict())

    def load_state_dict(self, ck: dict) -> None:
        self.gen.load_state_dict(ck["generator"])
        for k in ("mpd", "mrd", "opt_g", "opt_d", "sched_g", "sched_d"):
            getattr(self, k).load_state_dict(ck[k])

    def export(self, path: Path, step: int) -> None:
        """Same layout as the released ``bigvgan_generator.pt`` (weight norm kept) + the hparams to rebuild it."""
        h = {k: v for k, v in self.gen.h.items() if k != "use_cuda_kernel"}
        save_checkpoint(path, generator=self.gen.state_dict(), hparams=h, repo=self.repo, step=step)


def latent_windows(latents: torch.Tensor, audio: torch.Tensor, frame_len: torch.Tensor, repeat: int, segment: int,
                   context: int, hop: int, right: int = 1):
    """Random training windows for a VAE decoder, on VAE-frame boundaries.

    ``latents``: ``[B, dim, T]`` with every VAE frame repeated ``repeat`` times (``extract-latents``), ``frame_len``
    their lengths; ``audio``: ``[B, S]`` recordings with ``hop`` samples per VAE frame. Item ``i`` gets a segment of
    ``segment`` VAE frames from a random VAE frame ``s`` (with at least one more frame after it) and a decoder window
    of ``width = context + segment + right`` VAE frames from ``a = clamp(s - context, 0, n - width)``: ``context``
    frames of left context and ``right`` frames of right context, or the utterance start / end, which the decoder
    then sees as it does when decoding a whole utterance. A causal decoder needs no right context: ``right = 1``
    serves the resampler. A non-causal decoder needs both sides.

    Returns the windows ``[B, dim, width]`` (repeats averaged back, as ``LatentVocoder`` does), the offset of each
    segment in its window (``s - a`` VAE frames) and the target audio ``[B, segment * hop]`` (samples
    ``[s * hop, (s + segment) * hop)``)."""
    if repeat > 1:
        latents = F.avg_pool1d(latents[..., : latents.shape[-1] // repeat * repeat], repeat)
    n = frame_len.cpu() // repeat
    width = context + segment + right
    if (n < width).any():
        raise ValueError(f"utterances of {int(n.min())} VAE frames are shorter than a window of {width}")
    starts = (torch.rand(len(n)) * (n - segment).float()).long()  # s in [0, n - segment - 1]
    lefts = torch.minimum((starts - context).clamp_min(0), n - width)
    z = torch.stack([latents[i, :, a: a + width] for i, a in enumerate(lefts.tolist())])
    y = torch.stack([audio[i, s * hop: (s + segment) * hop] for i, s in enumerate(starts.tolist())])
    return z, (starts - lefts).to(latents.device), y


def discriminator_hparams(repo: str, overrides: dict | None = None) -> dict:
    """``config.json`` of a BigVGAN repo (the discriminators' hyperparameters), with ``overrides``."""
    import json

    from huggingface_hub import hf_hub_download

    return {**json.loads(Path(hf_hub_download(repo, "config.json")).read_text()), **(overrides or {})}


class VAEDecoderGAN(BigVGANGAN):
    """The decoder of an audio VAE (``vocoder.arch: vae_decoder``: VoxCPM2's causal AudioVAE decoder, DAC-VAE's
    non-causal, watermarked one) fine-tuned on generated latents with the BigVGAN-v2 recipe: NVIDIA's released 24 kHz
    MPD + CQT-D (and their AdamW state), LSGAN, feature matching and the multi-scale mel L1 (x15). Only the decoder is
    trained; the encoder is not used.

    * Input: denormalised latents, the ``repeat`` copies of every VAE frame averaged back (as ``LatentVocoder`` does
      at inference), so the decoder sees native 25 Hz frames.
    * Segments (:func:`latent_windows`): ``segment_frames`` VAE frames that start on a VAE frame, decoded in a window
      with ``context_frames`` frames of left context. A non-causal decoder also gets ``right_context_frames`` frames
      of right context (default: ``context_frames``); a causal one gets a single frame on the right, for the
      resampler. Only the segment's own samples are scored.
    * Trainable parameters: those the backend's ``trainable_decoder`` leaves trainable. DAC-VAE trains its audio path
      only: the watermark is frozen and still added to every output, in training as at inference. Every export checks
      that the frozen weights are still the released ones.
    * Output: the decoder's rate (48 kHz), resampled to 24 kHz inside the graph with the same band-limited sinc as
      ``LatentVocoder`` at inference (``torchaudio``), and compared with the 24 kHz recordings. The band above 12 kHz
      gets no training signal; the TTS pipeline never outputs it.
    * Weight norm: re-applied to every trainable convolution for training, as the VAE was trained
      (``vocoder.weight_norm``), and folded back on export.
    """

    export_name = "decoder_ft.pt"
    released_generator = False

    def __init__(self, cfg, device, backend: str, repeat: int):
        import torchaudio

        from .latents import load_backend

        self.cfg, vc, tc = cfg, cfg.vocoder, cfg.train
        self.repo = vc.get("repo", BIGVGAN_REPO)
        self.backend, self.repeat = backend, repeat
        self.be = load_backend(backend, device, **({"target_rate": vc.target_rate} if vc.get("target_rate") else {}))
        self.target_rate = int(getattr(self.be, "target_rate", None) or self.be.output_rate)
        self.gen = self.be.trainable_decoder().train()
        # the frozen part of the decoder (DAC-VAE: the watermark), as released: every export checks it is unchanged
        self.frozen = {k: v.detach().cpu().clone() for k, v in self.gen.named_parameters() if not v.requires_grad}
        self.weight_norm = vc.get("weight_norm", True)
        if self.weight_norm:
            self._apply_weight_norm()
        self.hop = round(SAMPLE_RATE / self.be.frame_rate)  # 24 kHz samples per VAE frame (960 at 25 Hz)
        self.segment, self.context = tc.segment_frames, tc.get("context_frames", 0)
        self.right = 1 if self.be.causal else max(1, tc.get("right_context_frames", self.context))
        self.min_frames = repeat * (self.context + self.segment + self.right)
        self.resample = torchaudio.transforms.Resample(self.be.output_rate, SAMPLE_RATE).to(device)
        self._setup(discriminator_hparams(self.repo, vc.get("hparams")), device)
        trained = sum(p.numel() for p in self.gen.parameters() if p.requires_grad)
        print(f"decoder: {trained / 1e6:.1f}M parameters trained, "
              f"{sum(v.numel() for v in self.frozen.values()) / 1e6:.1f}M frozen", flush=True)

    @torch.no_grad()
    def _apply_weight_norm(self) -> None:
        """Weight norm (``dim=0``) on every convolution of the decoder, from the released magnitudes and directions
        where the backend knows them (``decoder_weight_norm``); else from the weights (``v = w``, ``g = |w|``)."""
        released = self.be.decoder_weight_norm()
        n = 0
        for name, m in self.gen.named_modules():
            if not isinstance(m, (torch.nn.Conv1d, torch.nn.ConvTranspose1d)) or not m.weight.requires_grad:
                continue  # frozen convolutions stay as they are
            w = m.weight.detach().clone()
            torch.nn.utils.parametrizations.weight_norm(m)
            p = m.parametrizations.weight
            if name in released and released[name][0].shape == p.original0.shape:
                g0, v0 = p.original0.clone(), p.original1.clone()
                p.original0.copy_(released[name][0])
                p.original1.copy_(released[name][1])
                if torch.allclose(m.weight, w, rtol=1e-3, atol=1e-6):
                    n += 1
                else:  # not the released decoder: keep the folded weights
                    p.original0.copy_(g0)
                    p.original1.copy_(v0)
        if released:
            print(f"weight norm: {n} convolutions start from the released magnitudes and directions", flush=True)

    def segments(self, latents: torch.Tensor, audio: torch.Tensor, frame_len: torch.Tensor):
        z, offsets, y = latent_windows(latents, audio, frame_len, self.repeat, self.segment, self.context, self.hop,
                                       self.right)
        return (z, offsets), y

    def audio_samples(self, frames: int) -> int:
        return frames // self.repeat * self.hop

    def forward(self, x) -> torch.Tensor:
        z, offsets = x
        wav = self.resample(self.be.decode_train(z.float()))  # [B, window * hop] at 24 kHz
        idx = offsets[:, None] * self.hop + torch.arange(self.segment * self.hop, device=wav.device)
        return wav.gather(1, idx)[:, None]

    @torch.no_grad()
    def generate(self, latents: torch.Tensor) -> torch.Tensor:
        """Whole utterances ``[B, dim, T]`` (repeated frames) -> ``[B, samples]`` at 24 kHz."""
        z = F.avg_pool1d(latents[..., : latents.shape[-1] // self.repeat * self.repeat], self.repeat)
        return self.resample(self.be.decode_train(z.float()))

    def export(self, path: Path, step: int) -> None:
        """``{"decoder": state dict (weight norm folded), "backend", "target_rate", "sample_rate", "step"}``: tensors
        and numbers only, loadable with ``weights_only=True`` (``LatentVocoder(decoder=...)``). The state holds the
        frozen weights too (DAC-VAE: the watermark), which must still be the released ones."""
        # the weights are read from the parametrized modules: removing the parametrization from a copy would delete
        # the ``weight`` property of the class it shares with the training modules
        state, tag = {}, ".parametrizations.weight.original"
        with torch.no_grad():
            for k, v in self.gen.state_dict().items():
                if tag not in k:
                    state[k] = v.detach().cpu().clone()
                elif k.endswith(tag + "0"):
                    prefix = k[: k.index(tag)]
                    state[f"{prefix}.weight"] = self.gen.get_submodule(prefix).weight.detach().cpu().clone()
        changed = [k for k, v in self.frozen.items() if not torch.equal(state[k], v)]
        if changed:
            raise RuntimeError(f"frozen decoder weights changed in training: {', '.join(changed[:5])}")
        save_checkpoint(path, decoder=state, backend=self.backend, target_rate=self.target_rate,
                        sample_rate=SAMPLE_RATE, step=step)


class DriftVocoder:
    """A vocoder trained without a discriminator (``vocoder.objective: drift``, ``drift_vocoder.py``).

    ``S = drift.samples`` waveforms ``G(mel, z)`` per mel segment, ``z`` Gaussian noise channels at the frame rate, are
    drifted towards the real segment in a frozen feature space (``features``), plus ``mel_loss_coeff`` x the multi-scale
    mel L1 of every sample. ``vocoder.arch``: Vocos (pretrained ``vocoder.init``; ``same`` ISTFT padding on bigvgan
    mels) or a BigVGAN generator (``vocoder.repo``). AdamW, per-step exponential LR decay, one clipped gradient.
    ``generate`` and the export run at ``z = 0``, so the exported vocoder is deterministic and streams like a GAN one.
    """

    disc_label = "frozen feature nets"

    def __init__(self, cfg, device, mel: str = "bigvgan", arch: str = "vocos"):
        from .drift_vocoder import PAIRINGS, NoisyVocoder, build_feature_space

        self.cfg, vc, tc, dc = cfg, cfg.vocoder, cfg.train, cfg.drift
        self.mel, self.backend = mel, arch
        self.export_name = "vocos_ft.pt" if arch == "vocos" else "bigvgan_ft.pt"
        if arch == "vocos":
            net = build_vocos(vc.init)
            if mel == "bigvgan":  # F frames <-> F * hop samples, frame i centred on i * hop + hop / 2
                net.head.istft.padding = "same"
        else:
            self.repo = vc.get("repo", BIGVGAN_REPO)
            net = build_bigvgan(self.repo, vc.get("hparams"), pretrained=vc.get("pretrained", True))
            if tc.get("compile", False):
                for m in net.modules():
                    if type(m).__name__ == "Activation1d":
                        m.compile()
        self.gen = NoisyVocoder(net, vc.get("noise_channels", 8)).to(device).train()
        self.features = build_feature_space(cfg.features).to(device)
        self.mel_loss = bd.MultiScaleMelLoss(SAMPLE_RATE).to(device)
        self.pairing = {k: float(w) for k, w in dc.get("pairing", {"conditional": 1.0}).items()}
        mode = dc.get("mode", "official")
        if mode not in ("official", "kyutai"):
            raise ValueError(f"drift.mode must be official or kyutai, got {mode!r}")
        self.taus = None
        groups = [{"params": list(self.gen.parameters())}]
        if mode == "kyutai":  # one learned temperature per pairing, no weight decay (as in train.py)
            init = float(dc.get("kyutai", {}).get("tau_init", 1.0))
            self.taus = torch.nn.ParameterDict({k: torch.nn.Parameter(torch.tensor(init, device=device))
                                                for k in PAIRINGS if self.pairing.get(k)})
            groups.append({"params": list(self.taus.parameters()), "weight_decay": 0.0})
        self.opt = torch.optim.AdamW(groups, tc.lr, betas=tuple(tc.get("betas", (0.8, 0.99))))
        self.sched = torch.optim.lr_scheduler.ExponentialLR(self.opt, tc.get("lr_decay", 1.0))
        self.n_gen, self.n_disc = count_params(self.gen), count_params(self.features)
        # cuDNN autotuning over the ~50 frozen conv shapes: a 12 GB workspace spike and a slower step (RTX 5090)
        self.cudnn_benchmark = tc.get("cudnn_benchmark", False)

    def segments(self, mel: torch.Tensor, audio: torch.Tensor, mel_len: torch.Tensor):
        return random_segments(mel, audio, mel_len, self.cfg.train.segment_frames, self.mel)

    def audio_samples(self, frames: int) -> int:
        return segment_samples(frames, self.mel)

    def generate(self, mel: torch.Tensor) -> torch.Tensor:
        """``z = 0`` (the exported vocoder); eager, so variable lengths do not trigger recompilation."""
        with torch.compiler.set_stance("force_eager") if self.cfg.train.get("compile") else nullcontext():
            return self.gen(mel)

    def drift_grad(self, wave: torch.Tensor, audio: torch.Tensor, B: int) -> tuple[torch.Tensor, torch.Tensor, dict]:
        """Gradient of the drift loss w.r.t. the waveforms ``[B * S, n]`` (and the temperatures' ``.grad``), one
        feature-space part at a time: only one part's graph is alive. Returns the gradient, the loss and its info."""
        from .drift_vocoder import map_weight_sum, shifted_views, split_samples, vocoder_drift_loss

        dc = self.cfg.drift
        reduce, kw = dc.get("reduce", "mean"), dc.get("key_weights")
        x = wave.detach().requires_grad_()
        with torch.no_grad():
            views = shifted_views(audio, dc.get("pos_shifts") or ()).flatten(0, 1)
        total, weights, info = 0.0, 0.0, {}
        for part in self.features.parts():
            with torch.no_grad():
                pos = split_samples(part(views), B)
            gen = split_samples(part(x), B)
            loss, inf = vocoder_drift_loss(gen, pos, self.pairing, dc.get("temperatures", (0.02, 0.05, 0.2)), kw,
                                           "sum", dc.get("max_locations"), dc.get("pooled_locations", 128),
                                           self.taus, dc.get("affinity_floor", 1e-6))
            loss.backward()
            total, weights = total + loss.detach(), weights + map_weight_sum(gen, kw)
            for k, v in inf.items():  # per-map stats; the temperature losses (one per pairing) add up over the parts
                info[k] = info[k] + v if k.endswith("tau_loss") and k in info else v
        norm = weights if reduce == "mean" else 1.0
        for t in [] if self.taus is None else self.taus.values():
            t.grad = t.grad * self.cfg.train.drift_coeff / norm
        info.update({k: v / norm for k, v in info.items() if k.endswith("tau_loss")})
        return x.grad / norm, total / norm, info

    def step(self, mel: torch.Tensor, audio: torch.Tensor, step: int) -> dict:
        from .drift_vocoder import summarize

        tc, dc = self.cfg.train, self.cfg.drift
        B, S = mel.shape[0], dc.samples
        z = torch.randn(B * S, self.gen.noise_channels, mel.shape[-1], device=mel.device)
        wave = self.gen(mel.repeat_interleave(S, 0), z)  # [B * S, n], segment-major
        n = min(wave.shape[-1], audio.shape[-1])
        wave, audio = wave[:, :n], audio[:, :n]
        self.opt.zero_grad(set_to_none=True)
        grad, l_drift, info = self.drift_grad(wave, audio, B)
        with nullcontext() if tc.mel_loss_coeff > 0 else torch.no_grad():
            l_mel = self.mel_loss(wave, audio.repeat_interleave(S, 0))
        # d/dwave of drift_coeff * drift loss is drift_coeff * grad: one backward through the generator
        surrogate = tc.drift_coeff * (wave * grad).sum() + (tc.mel_loss_coeff * l_mel if tc.mel_loss_coeff > 0 else 0)
        surrogate.backward()
        loss = tc.drift_coeff * l_drift + tc.mel_loss_coeff * l_mel.detach()
        gn = torch.nn.utils.clip_grad_norm_(self.gen.parameters(), tc.grad_clip)
        self.opt.step()
        self.sched.step()
        with torch.no_grad():  # across-sample std of the log-mel: 0 = the noise is ignored (collapse)
            lm = self.mel_loss.log_mel(wave.detach().float(), 1024)
            spread = lm.view(B, S, *lm.shape[1:]).std(1).mean()
        metrics = {"loss": loss.item(), "drift": l_drift.item(), "mel": l_mel.item(), "spread": spread.item(),
                   "grad": gn.item(), "lr": self.sched.get_last_lr()[0]}
        metrics.update(summarize(info))
        return metrics

    def state_dict(self) -> dict:
        return dict(generator=self.gen.net.state_dict(), opt=self.opt.state_dict(), sched=self.sched.state_dict(),
                    taus=None if self.taus is None else self.taus.state_dict())

    def load_state_dict(self, ck: dict) -> None:
        self.gen.net.load_state_dict(ck["generator"])
        self.opt.load_state_dict(ck["opt"])
        self.sched.load_state_dict(ck["sched"])
        if self.taus is not None and ck.get("taus"):
            self.taus.load_state_dict(ck["taus"])

    def export(self, path: Path, step: int) -> None:
        """The GAN fine-tunes' layouts (Vocos: ``vocos``, ``init``, ``mel``, ``head_padding``; BigVGAN: ``generator``,
        ``repo``, ``hparams``) plus ``noise_channels``: :class:`~drifting_tts.vocoder.Vocoder` runs it at ``z = 0``."""
        net, k = self.gen.net, self.gen.noise_channels
        if self.backend == "vocos":
            save_checkpoint(path, vocos=net.state_dict(), init=self.cfg.vocoder.init, step=step, mel=self.mel,
                            head_padding=net.head.istft.padding, noise_channels=k, objective="drift")
        else:
            h = {key: v for key, v in net.h.items() if key != "use_cuda_kernel"}
            save_checkpoint(path, generator=net.state_dict(), hparams=h, repo=self.repo, step=step, noise_channels=k,
                            objective="drift")


def build_trainer(cfg, device, arch: str, mel: str):
    """``vocoder.objective``: ``gan`` (default: :class:`VocosGAN` / :class:`BigVGANGAN`) or ``drift``."""
    objective = cfg.vocoder.get("objective", "gan")
    if objective not in OBJECTIVES:
        raise ValueError(f"vocoder.objective must be one of {OBJECTIVES}, got {objective!r}")
    if objective == "drift":
        return DriftVocoder(cfg, device, mel=mel, arch=arch)
    return BigVGANGAN(cfg, device) if arch == "bigvgan" else VocosGAN(cfg, device, mel=mel)


@torch.no_grad()
def log_samples(gan, tts, batch: dict, stats: MelStats, tc, writer, step: int, device) -> None:
    """Full validation utterances: the vocoder on GTA mels and on recorded mels, plus the real audio."""
    gta = stats.denormalize(gta_mels(tts, batch, tc.gta_temperature, device, cfg_scale=tc.get("gta_cfg", 1.0)))
    rec = stats.denormalize(batch["mel"].to(device))
    for i, n in enumerate(batch["mel_len"].tolist()):
        for name, mel in (("gta", gta), ("recorded_mel", rec)):
            wav = gan.generate(mel[i: i + 1, :, :n])[0].clamp(-1, 1).float().cpu()
            writer.add_audio(f"{name}/{i}", wav, step, sample_rate=SAMPLE_RATE)
        writer.add_audio(f"real/{i}", batch["audio"][i, : gan.audio_samples(n)], step, sample_rate=SAMPLE_RATE)


def run(args) -> None:
    from torch.utils.tensorboard import SummaryWriter

    from .latents import VAE_BACKENDS
    from .train import load_tts

    cfg = load_config(args.config, args.overrides)
    work = Path(args.workdir)
    work.mkdir(parents=True, exist_ok=True)
    save_config(cfg, work / "config.yaml")
    tc = cfg.train
    seed_everything(tc.seed)
    device = "cuda" if torch.cuda.is_available() and not tc.get("cpu", False) else "cpu"

    tts, tts_cfg, stats = load_tts(cfg.tts.path, device)
    backend = stats.get("backend", "vocos")  # the mel type (or VAE latents) the TTS model was trained on
    if cfg.vocoder.get("backend", backend) != backend:
        raise ValueError(f"config asks for {cfg.vocoder.backend} mels but the TTS model was trained on "
                         f"{backend} mels (`prepare --backend`)")
    vae = backend in VAE_BACKENDS
    arch = cfg.vocoder.get("arch", "vae_decoder" if vae else backend)  # a Vocos can also learn BigVGAN mels
    if vae and arch not in ("vae_decoder", backend):
        raise ValueError(f"a TTS model trained on {backend} latents fine-tunes its VAE decoder "
                         f"(vocoder.arch: vae_decoder), not a {arch} vocoder")
    if not vae and arch == "vae_decoder":
        raise ValueError(f"vocoder.arch: vae_decoder needs a TTS model trained on VAE latents, not {backend} mels")
    if arch == "bigvgan" and backend != "bigvgan":
        raise ValueError("a BigVGAN vocoder needs a TTS model trained on bigvgan mels")
    tts.requires_grad_(False)
    mel_stats = MelStats(stats["mean"], stats["std"])  # one scalar for log-mels, per channel for latents
    if vae:
        if cfg.vocoder.get("objective", "gan") != "gan":
            raise ValueError("a VAE decoder is fine-tuned with the GAN objective (vocoder.objective: gan)")
        gan = VAEDecoderGAN(cfg, device, backend, repeat=stats.get("latent_repeat", 1))
    else:
        gan = build_trainer(cfg, device, arch, backend)
    min_frames = getattr(gan, "min_frames", tc.segment_frames)
    d = cfg.data
    ds = MelDataset(d.root, "train", min_quality=d.min_quality, min_frames=min_frames, max_frames=d.max_frames,
                    with_audio=True, with_f0=tts.pitch_enabled, filters=d.get("filters"))
    sampler = BucketBatchSampler([ds.frames(i) for i in range(len(ds))], max_frames=tc.batch_frames,
                                 max_batch=tc.batch_size, seed=tc.seed)
    loader = DataLoader(ds, batch_sampler=sampler, collate_fn=collate, num_workers=tc.num_workers,
                        pin_memory=True, persistent_workers=tc.num_workers > 0)
    print(f"{arch} vocoder on {backend} {'latents' if vae else 'mels'} {gan.n_gen:.1f}M, "
          f"{getattr(gan, 'disc_label', 'discriminators')} {gan.n_disc:.1f}M, {len(ds)} utterances", flush=True)
    writer = SummaryWriter(work / "tb")
    samples = None
    if tc.get("sample_every", 0) > 0:
        val = MelDataset(d.root, "val", min_frames=min_frames, max_frames=d.max_frames, with_audio=True,
                         with_f0=tts.pitch_enabled)
        val = val if len(val) else ds
        samples = collate([val[i] for i in range(min(tc.get("num_samples", 2), len(val)))])

    step = 0
    if (work / "last.pt").exists():
        ck = torch.load(work / "last.pt", map_location="cpu", weights_only=False)
        gan.load_state_dict(ck)
        step = ck["step"]
        sampler.epoch = ck.get("epoch", 0)
        print(f"resumed from step {step}", flush=True)
    elif tc.get("init_from"):
        if not hasattr(gan, "init_from"):
            raise ValueError("train.init_from is supported for vocoder.arch: vocos (GAN) only")
        gan.init_from(tc.init_from)

    it = infinite(loader)
    t0, agg = time.time(), {}
    while step < tc.steps:
        batch = next(it)
        use_gta = torch.rand(()) < tc.gta_prob
        mel = gta_mels(tts, batch, tc.gta_temperature, device, cfg_scale=tc.get("gta_cfg", 1.0)) if use_gta \
            else batch["mel"].to(device)
        mel = mel_stats.denormalize(mel)  # back to log-mels / latents, the vocoder's input
        x, audio = gan.segments(mel, batch["audio"].to(device), batch["mel_len"])
        # fixed segment shapes: faster convolutions (GAN; the drift trainer opts out, see DriftVocoder)
        with torch.backends.cudnn.flags(enabled=True, benchmark=getattr(gan, "cudnn_benchmark", True)):
            gan.batch_is_gta = bool(use_gta)
            metrics = gan.step(x, audio, step)
        step += 1
        if "mel" in metrics:  # the mel loss on generated and on recorded frames, separately
            metrics[f"mel_{'gta' if use_gta else 'recorded'}"] = metrics["mel"]
        for k, v in metrics.items():
            total, count = agg.get(k, (0.0, 0))
            agg[k] = (total + v, count + 1)
        if step % tc.log_every == 0:
            for k, (v, c) in agg.items():
                writer.add_scalar(f"vocoder/{k}", v / c, step)
            rate = tc.log_every / (time.time() - t0)
            mem = f", {torch.cuda.max_memory_allocated() / 2**30:.1f} GB" if device == "cuda" else ""
            print(f"step {step} " + " ".join(f"{k}={v / c:.4g}" for k, (v, c) in agg.items())
                  + f" ({rate:.2f} it/s{mem})", flush=True)
            t0, agg = time.time(), {}
        if samples is not None and step % tc.sample_every == 0:
            log_samples(gan, tts, samples, mel_stats, tc, writer, step, device)
        if step % tc.save_every == 0 or step == tc.steps:
            save_checkpoint(work / "last.pt", step=step, epoch=sampler.epoch, **gan.state_dict())
            gan.export(work / gan.export_name, step)
            if tc.get("keep_snapshots", False):  # every export also as <name>_<step>, e.g. decoder_ft_2500.pt
                name = Path(gan.export_name)
                shutil.copyfile(work / name, work / f"{name.stem}_{step}{name.suffix}")
    print(f"done: {work / gan.export_name}", flush=True)
